# Generated by Django 6.1.1 on 2026-09-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('usuarios', models.ManyToManyField(related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id_item_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(max_length=50)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_despesa', models.DateField()),
                ('tipo_despesa', models.CharField(choices=[('CUSTEIO', 'Custeio'), ('CAPITAL', 'Capital')], max_length=10)),
                ('item_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemorcamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.projeto')),
            ],
        ),
    ]
